.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH GXTUNER 1 "December 20, 2017"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
\fBgxtuner\fP \- a tuner for jackd
.SH SYNOPSIS
.B gxtuner
.SH DESCRIPTION
This manual page documents briefly the
\fBgxtuner\fP program.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBgxtuner\fP is a simple, small and lightweight tuner, for 12 TET and extended Just Intonation, connected through Jack Audio Connection Kit.
.PP
\fBgxtuner\fP comes with a analogue like interface (scale), show the tune (char) and the accumulated frequency (Hz).
.SH OPTIONS
.PP
.B \  -h            
       Display short info
.PP
.B \  -\-help\-all  
       Show all help options
.PP
.B \  -\-help\-gtk  
       GTK configuration options
.PP
.B \  -\-help\-jack  
       JACK configuration options
.PP
.B \  -\-help\-engine  
       ENGINE configuration options
.PP
GTK configuration options
.PP
.B \   -x \-\-posx=POSITION_X
        window position x\-axis ( \-x 1 \-> . .)
.PP
.B \   -y \-\-posy=POSITION_Y
        window position y\-axis ( \-y 1 \-> . . )
.PP
.B \   -w \-\-width=WIDTH
        'default' width ( \-w 500 \-> . .)
.PP
.B \   -l \-\-height=HEIGHT
        'default' height ( \-l 300 \-> . .)
.PP
.B \   -d \-\-desktop=NUM
        set to virtual desktop num
.PP
JACK configuration options
.PP
.B \  -i   \-\-jack\-input=PORT  
       gxtuner JACK input
       e.g.
       gxtuner \-i system:capture_1
       gxtuner \-i gx_head_amp:out_0
.PP
.B \  -U    \-\-jack\-jack\-input=UUID            
       gxtuner JACK session UUID
.PP
ENGINE configuration options
.PP
.B \  -p    \-\-pitch=PITCH
       set reference pitch ( \-p 400.0 <\-> 600.0)
.PP
.B \  -t    \-\-threshold=THRESHOLD
       set threshold level (\-t 0.001 <\-> 0.2)
.PP
.B \  -m    \-\-mode=MODE
       set tuner mode ( \-m chromatic , scale3diatonic , scale35chromatic , scale357chromatic , scale37chromatic , scaleovertones , scale16limit )
.PP
.B \ -R \-\-reference_note=REFERENCE_NOTE
        set reference note ( \-R C , D , E , F , G , A , B )
.PP
.B \ -A \-\-reference_03comma=REFERENCE_03COMMA        
        set reference 3 limit comma ( \-A min3 , min2 , min1 , 0 , 1 , 2 , 3 )
.PP
.B \ -B \-\-reference_05comma=REFERENCE_05COMMA        
        set reference 5 limit comma ( \-B min3 , min2 , min1 , 0 , 1 , 2 , 3 )
.PP
.B \ -C \-\-reference_07comma=REFERENCE_07COMMA        
        set reference 7 limit comma ( \-C min3 , min2 , min1 , 0 , 1 , 2 , 3 )
.PP
.B \ -D \-\-reference_11comma=REFERENCE_11COMMA        
        set reference 11 limit comma ( \-D min3 , min2 , min1 , 0 , 1 , 2 , 3 )
.PP
.B \ -E \-\-reference_13comma=REFERENCE_13COMMA        
        set reference 13 limit comma ( \-E min3 , min2 , min1 , 0 , 1 , 2 , 3 )
.PP
.B \ -F \-\-reference_17comma=REFERENCE_17COMMA        
        set reference 17 limit comma ( \-F min3 , min2 , min1 , 0 , 1 , 2 , 3 )
.PP
.B \ -G \-\-reference_19comma=REFERENCE_19COMMA        
        set reference 19 limit comma ( \-G min3 , min2 , min1 , 0 , 1 , 2 , 3 )
.PP
.B \ -H \-\-reference_23comma=REFERENCE_23COMMA        
        set reference 23 limit comma ( \-H min3 , min2 , min1 , 0 , 1 , 2 , 3 )
.PP
.B \ -I \-\-reference_29comma=REFERENCE_29COMMA        
        set reference 29 limit comma ( \-I min3 , min2 , min1 , 0 , 1 , 2 , 3 )
.PP
.B \ -J \-\-reference_31comma=REFERENCE_31COMMA        
        set reference 31 limit comma ( \-J min3 , min2 , min1 , 0 , 1 , 2 , 3 )
.PP
.SH SEE ALSO
.BR jackd(1).
.br
.SH AUTHOR
This manual page was written by Jaromír Mikeš <mira.mikes@seznam.cz> and Hans Bezemer <allfifthstuning@kliksafe.nl>,
for the Debian project (but may be used by others).
